Controllers/OgrenciController.cs
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using EntityFreamwork.Models;
using EntityFreamwork.Data;
using Microsoft.EntityFrameworkCore;


namespace EntityFreamwork.Controllers;

public class OgrenciController : Controller
{
    private readonly DataContext _context;
    public OgrenciController(DataContext context)
    {
        _context = context;
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpGet]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var ogr = await _context.Ogrenciler.
        Include(o=>o.KursKayitlari).
        ThenInclude(o=>o.Kurs).
        FirstOrDefaultAsync(o=>o.OgrenciId==id);
        if (ogr == null)
        {
            return NotFound();
        }
        return View(ogr);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Ogrenci model)
    {
        if (id != model.OgrenciId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(model);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.Ogrenciler.Any(o => o.OgrenciId == model.OgrenciId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }

            }
            return RedirectToAction("Index");
        }
        return View(model);
    }
    public async Task<IActionResult> Index()
    {
        var ogrenciler = await _context.Ogrenciler.ToListAsync();
        return View(ogrenciler);

    }
    [HttpPost]
    public async Task<IActionResult> Create(Ogrenci model)
    {
        _context.Ogrenciler.Add(model);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var ogrenci = await _context.Ogrenciler.
        Include(o => o.KursKayitlari).
        ThenInclude(o => o.Kurs).
        FirstOrDefaultAsync(o => o.OgrenciId == id);
        if (ogrenci == null)
        {
            return NotFound();
        }
        return View(ogrenci);

    }
    [HttpPost]
    public async Task<IActionResult> Delete([FromForm] int id)
    {
        var ogrenci = await _context.Ogrenciler.FindAsync(id);
        if (ogrenci == null)
        {
            return NotFound();
        }
        _context.Ogrenciler.Remove(ogrenci);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");

    }



}

Views/Ogrenci/Create.cshtml
@model Ogrenci
<h2>Öğrenci Ekle</h2>
<hr>
<form asp-controller="Ogrenci" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciAd" class="form-label">Öğrenci Adı</label>
        <input asp-for="OgrenciAd" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="OgrenciSoyad" class="form-label">Öğrenci Soyadı</label>
        <input asp-for="OgrenciSoyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">Eposta</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>

Views/Ogrenci/Delete.cshtml
@model Ogrenci

<p>
    <b>
        @Model.OgrenciAd 
    </b>
    adlı öğrenciyi silmek istiyoru musunuz?
    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.OgrenciId" name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a>
    </form>


</p>

Views/Ogrenci/Edit.cshtml
@model Ogrenci
<h2>Öğrenci Güncelle</h2>
<hr>
<div class="row">
<div class="col-8">
    <form asp-controller="Ogrenci" asp-action="Edit" method="post">
    <input type="hidden" asp-for="OgrenciId">
    <div class="mb-3">
        <label asp-for="OgrenciAd" class="form-label">Öğrenci Adı</label>
        <input asp-for="OgrenciAd" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="OgrenciSoyad" class="form-label">Öğrenci Soyadı</label>
        <input asp-for="OgrenciSoyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">Eposta</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>
</div>
<div class="col-4">
    <h4>Kurslar</h4>
    <hr>
    <ul>
        @foreach(var item in @Model.KursKayitlari){
         <li>
            @item.Kurs.Baslik
         </li>
        }
    </ul>
</div>

</div>

Views/Ogrenci/Index.cshtml
@model IEnumerable<Ogrenci>
<h2>Öğrenci Listesi</h2>
<hr>
<a href="/Ogrenci/Create" class="btn btn-sm btn-outline-primary">Öğrenci Ekle</a>

<table class="table">
    <thead>
        <th>
            @Html.DisplayNameFor(m=>m.OgrenciId)
        </th>
          <th>
             @Html.DisplayNameFor(m=>m.OgrenciAd)
        
        </th>
          <th>
              @Html.DisplayNameFor(m=>m.OgrenciSoyad)
        
        </th>
          <th>
             @Html.DisplayNameFor(m=>m.Eposta)
          
        </th>
          <th>
            @Html.DisplayNameFor(m=>m.Telefon)
    
        </th>
    </thead>
<tbody>
    @foreach(var ogrenci in Model){
        <tr>
            <td>@ogrenci.OgrenciId</td>
             <td>@ogrenci.OgrenciAd</td>
              <td>@ogrenci.OgrenciSoyad</td>
               <td>@ogrenci.Eposta</td>
                <td>@ogrenci.Telefon</td>
                <td>
                    <a asp-controller="Ogrenci" asp-action="Edit" asp-route-id="@ogrenci.OgrenciId" class="btn btn-sm btn btn-success">Edit</a>
                    <a asp-controller="Ogrenci" asp-action="Delete" asp-route-id="@ogrenci.OgrenciId" class="btn btn-sm btn btn-danger">Delete</a>
                </td>

        </tr>
    }
</tbody>


</table>