Controllers/OgretmenController.cs
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using EntityFreamwork.Models;
using EntityFreamwork.Data;
using Microsoft.EntityFrameworkCore;

namespace EntityFreamwork.Controllers;
public class OgretmenController : Controller
{
    private readonly DataContext _context;
    public OgretmenController(DataContext context)
    {
        _context = context;
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpGet]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var ogr = await _context.
        Ogretmenler.FindAsync(id);
        if (ogr == null)
        {
            return NotFound();
        }
        return View(ogr);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Ogretmen model)
    {
        if (id != model.OgretmenId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(model);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.Ogretmenler.Any(o => o.OgretmenId == model.OgretmenId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }

            }
            return RedirectToAction("Index");
        }
        return View(model);
    }
    public async Task<IActionResult> Index()
    {
        var ogretmenler = await _context.Ogretmenler.ToListAsync();
        return View(ogretmenler);

    }
    [HttpPost]
    public async Task<IActionResult> Create(Ogretmen model)
    {
        _context.Ogretmenler.Add(model);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var ogrenci = await _context.
        Ogretmenler.FindAsync(id);
        if (ogrenci == null)
        {
            return NotFound();
        }
        return View(ogrenci);

    }
    [HttpPost]
    public async Task<IActionResult> Delete([FromForm] int id)
    {
        var ogrenci = await _context.Ogretmenler.FindAsync(id);
        if (ogrenci == null)
        {
            return NotFound();
        }
        _context.Ogretmenler.Remove(ogrenci);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");

    }



}

Views/Ogretmen/Create.cshtml
@model Ogretmen
<h2>Ogretmen Ekle</h2>
<hr>
<form asp-controller="Ogretmen" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Ad" class="form-label">Öğrenci Adı</label>
        <input asp-for="Ad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Soyad" class="form-label">Öğrenci Soyadı</label>
        <input asp-for="Soyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">Eposta</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>

Views/Ogretmen/Delete.cshtml
@model Ogretmen

<p>
    <b>
        @Model.Ad 
    </b>
    adlı öğretmeni silmek istiyoru musunuz?
    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.OgretmenId" name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a>
    </form>


</p>

Views/Ogretmen/Edit.cshtml
@model Ogretmen
<h2>Öğretmen Güncelle</h2>
<hr>
<div class="row">
<div class="col-8">
    <form asp-controller="Ogretmen" asp-action="Edit" method="post">
    <input type="hidden" asp-for="OgretmenId">
    <div class="mb-3">
        <label asp-for="Ad" class="form-label">Öğretmen Adı</label>
        <input asp-for="Ad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Soyad" class="form-label">Öğretmen Soyadı</label>
        <input asp-for="Soyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">Eposta</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>
</div>
<div class="col-4">
    <h4>Kurslar</h4>
    <hr>
    <ul>
        @foreach(var item in @Model.Kurslar){
         <li>
            @item.KursKayitlari
         </li>
        }
    </ul>
</div>

</div>

Views/Ogretmen/Index.cshtml
@model IEnumerable<Ogretmen>
<h2>Öğrenci Listesi</h2>
<hr>
<a href="/Ogretmen/Create" class="btn btn-sm btn-outline-primary">Öğretmen Ekle</a>

<table class="table">
    <thead>
        <th>
            @Html.DisplayNameFor(m=>m.OgretmenId)
        </th>
          <th>
             @Html.DisplayNameFor(m=>m.Ad)
        
        </th>
          <th>
              @Html.DisplayNameFor(m=>m.Soyad)
        
        </th>
          <th>
             @Html.DisplayNameFor(m=>m.Eposta)
          
        </th>
          <th>
            @Html.DisplayNameFor(m=>m.Telefon)
    
        </th>
    </thead>
<tbody>
    @foreach(var ogretmen in Model){
        <tr>
            <td>@ogretmen.OgretmenId</td>
             <td>@ogretmen.Ad</td>
              <td>@ogretmen.Soyad</td>
               <td>@ogretmen.Eposta</td>
                <td>@ogretmen.Telefon</td>
                <td>
                    <a asp-controller="Ogretmen" asp-action="Edit" asp-route-id="@ogretmen.OgretmenId" class="btn btn-sm btn btn-success">Edit</a>
                    <a asp-controller="Ogretmen" asp-action="Delete" asp-route-id="@ogretmen.OgretmenId" class="btn btn-sm btn btn-danger">Delete</a>
                </td>

        </tr>
    }
</tbody>


</table>