Controllers/KursController.cs
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using EntityFreamwork.Models;
using EntityFreamwork.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace EntityFreamwork.Controllers;

public class KursController : Controller
{
    private readonly DataContext _context;
    public KursController(DataContext context)
    {
        _context = context;
    }
    public async Task<IActionResult> Index()
    {
        var kurslar = await _context.Kurslar.ToListAsync();
        return View(kurslar);

    }
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var kurs = await _context.Kurslar.
        Include(k=>k.KursKayitlari).
        ThenInclude(k=>k.Ogrenci).
        FirstOrDefaultAsync(k=>k.KursId==id);
        if (kurs == null)
        {
            return NotFound();
        }
        return View(kurs);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Kurs model)
    {
        if (id != model.KursId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(model);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.Kurslar.Any(o => o.KursId == model.KursId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }

            }
            return RedirectToAction("Index");
        }
        return View(model);
    }
    public async Task<IActionResult> Create()
    {
        ViewBag.Ogrenciler = new SelectList(await _context.Ogretmenler.ToListAsync(), "OgretmenId", "Ad");
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(Kurs model)
    {
        _context.Kurslar.Add(model);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var kurs = await _context.Kurslar.FindAsync(id);
        if (kurs == null)
        {
            return NotFound();
        }
        return View(kurs);

    }
    [HttpPost]
    public async Task<IActionResult> Delete([FromForm] int id)
    {
        var kurs = await _context.Kurslar.FindAsync(id);
        if (kurs == null)
        {
            return NotFound();
        }
        _context.Kurslar.Remove(kurs);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");

    }


}

Views/Kurs/Delete.cshtml
@model Kurs

<p>
    <b>
        @Model.Baslik 
    </b>
    adlı kursu silmek istiyoru musunuz?
    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.KursId" name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a>
    </form>


</p>

Views/Kurs/Edit.cshtml
@model Kurs
<h2>Kurs Listesi</h2>
<div class="row">
<div class="col-8">
 <form asp-controller="Kurs" asp-action="Edit" method="post">
    <input type="hidden" asp-for="KursId">
   
    <div class="mb-3">
        <label asp-for="Baslik" class="form-label">Baslik</label>
        <input asp-for="Baslik" class="form-control">
    </div>
   
    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>
</div>
<div class="col-4">
    <h4>Kurslar</h4>
    <hr>
    <ul>
        @foreach(var item in @Model.KursKayitlari){
         <li>
            @item.Ogrenci.AdSoyad
         </li>
        }
    </ul>
</div>

</div>

Views/Kurs/Index.cshtml
@model IEnumerable<Kurs>
<h2>Kurs Listesi</h2>
<hr>
<a href="/Kurs/Create" class="btn btn-sm btn-outline-primary">Kurs Ekle</a>

<table class="table">
    <thead>
        <th>
            @Html.DisplayNameFor(m=>m.KursId)
        </th>
          <th>
             @Html.DisplayNameFor(m=>m.Baslik)
        
        
    </thead>
<tbody>
    @foreach(var kurs in Model){
        <tr>
            <td>@kurs.KursId</td>
             <td>@kurs.Baslik</td>
         
                <td>
                  <a asp-controller="Kurs" asp-action="Edit" asp-route-id="@kurs.KursId" class="btn btn-sm btn btn-success">Edit</a>
                    <a asp-controller="Kurs" asp-action="Delete" asp-route-id="@kurs.KursId" class="btn btn-sm btn btn-danger">Delete</a>
                </td>

        </tr>
    }
</tbody>


</table>