Controllers/KursKayıtController.cs
using EntityFreamwork.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;

namespace EntityFreamwork.Controllers
{
    public class KursKayitController : Controller
    {
        private readonly DataContext _context;

        public KursKayitController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {

            var kursKayitleri = await _context.KursKayit.Include(x => x.Ogrenci).Include(x => x.Kurs).ToListAsync();

            return View(kursKayitleri);
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Ogrenciler = new SelectList(await _context.Ogrenciler.ToListAsync(), "OgrenciId", "AdSoyad");
            ViewBag.Kurslar = new SelectList(await _context.Kurslar.ToListAsync(), "KursId", "Baslik");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(KursKayit model)
        {
            model.KayitTarihi = DateTime.Now;
            _context.KursKayit.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
         public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var kurs = await _context.KursKayit.FindAsync(id);
        if (kurs == null)
        {
            return NotFound();
        }
        return View(kurs);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, KursKayit model)
    {
        if (id != model.KayitId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(model);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.KursKayit.Any(o => o.KayitId == model.KayitId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }

            }
            return RedirectToAction("Index");
        }
        return View(model);
    }
   
    [HttpGet]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var kurs = await _context.KursKayit.FindAsync(id);
        if (kurs == null)
        {
            return NotFound();
        }
        return View(kurs);

    }
    [HttpPost]
    public async Task<IActionResult> Delete([FromForm] int id)
    {
        var kurs = await _context.KursKayit.FindAsync(id);
        if (kurs == null)
        {
            return NotFound();
        }
        _context.KursKayit.Remove(kurs);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");

    }



    }

}

Views/KursKayit/Create.cshtml
@model KursKayit
<h2>Kurs Kayıt Ekle</h2>
<hr>
<form asp-controller="KursKayit" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciId" class="form-label">Öğrenci</label>
        <select asp-for="OgrenciId" asp-items="ViewBag.Ogrenciler" class="form-control"></select>
        <option value="">Seçiniz</option>
    </div>
    <div class="mb-3">
        <label asp-for="KursId" class="form-label">Kurs</label>
        <select asp-for="KursId" asp-items="ViewBag.Kurslar" class="form-control"></select>
         <option value="">Seçiniz</option>
    </div>
    <br>
    <br>
    <br>
  
    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>

Views/KursKayit/Delete.cshtml
@model KursKayit

<p>
    <b>
        @Model.Ogrenci.OgrenciAd 
    </b>
    adlı öğrencinin 
    <b>
        @Model.Kurs.Baslik
    </b>
    kursunu silmek istiyor musunuz?
    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.KayitId" name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a>
    </form>


</p>

Views/KursKayit/Edit.cshtml
@model KursKayit
<h2>Kurs Kayıt Ekle</h2>
<hr>
<form asp-controller="KursKayit" asp-action="Create" method="post">
    <input type="hidden" asp-for="KayitId">
    <div class="mb-3">
        <label asp-for="OgrenciId" class="form-label">Öğrenci</label>
        <select asp-for="OgrenciId"  class="form-control"></select>
  
    </div>
    <div class="mb-3">
        <label asp-for="KursId" class="form-label">Kurs</label>
        <select asp-for="KursId"  class="form-control"></select>
      
    </div>
    <br>
    <br>
    <br>
  
    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>

Views/KursKayit/Index.cshtml
@model IEnumerable<KursKayit>

<h2>Kurs Kayıt Listesi</h2>

<hr>
<a href="/KursKayit/Create" class="btn btn-sm btn-outline-primary">Kurs Ekle</a>

<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">
                @Html.DisplayNameFor(m => m.KayitId)

            </th>
            <th>
                @Html.DisplayNameFor(m => m.Ogrenci.OgrenciAd)

            </th>
            <th>
                @Html.DisplayNameFor(m => m.Kurs.Baslik)

            </th>
            <th style="width: 150px;">

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model){
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KayitId)
                </td>
                 <td>
                    @Html.DisplayFor(modelItem => item.Ogrenci.OgrenciAd)
                </td>
                 <td>
                    @Html.DisplayFor(modelItem => item.Kurs.Baslik)
                </td>
                <td>
                    <a  asp-action="Edit" asp-route-id="@item.KayitId" class="btn btn-sm btn btn-success">Edit</a>
                    <a  asp-action="Delete" asp-route-id="@item.KayitId" class="btn btn-sm btn btn-danger">Delete</a>
                </td>
            </tr>

        }
    </tbody>
</table>